spring.application.name=sistemas

# Configuración de la base de datos SQL Server
#spring.datasource.url=jdbc:sqlserver://172.28.240.16:1433;databaseName=UTP2;encrypt=false;trustServerCertificate=true
spring.datasource.url=jdbc:sqlserver://SQL1004.site4now.net:1433;databaseName=db_abb271_desarrollog06;encrypt=false;trustServerCertificate=true
spring.datasource.username=db_abb271_desarrollog06_admin
spring.datasource.password=DesarrolloG06
spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver

# JPA/Hibernate 'update', 'none' o 'validate'
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.SQLServer2012Dialect

jwt.secret = 4f8d9b214a4c70f9b7b1777d6a3c09a6d82d5d4b9eaf4c2b6a80d1fd6e8b2a3e
jwt.expiration = 3600


jwt.expirationMs=3600000




spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

# spring.main.allow-bean-definition-overriding=true

##springdoc.api-docs.path=/api-docs
##springdoc.swagger-ui.path=/swagger-ui.html
##springdoc.swagger-ui.enabled=true
#
##springdoc.api-docs.path=/v3/api-docs
##springdoc.swagger-ui.path=/swagger-ui.html
##springdoc.swagger-ui.enabled=true
##springdoc.version=1.0.0  # Añade versión a tu API
#
## Configuración básica SpringDoc
#springdoc.swagger-ui.path=/swagger-ui.html
#springdoc.api-docs.path=/v3/api-docs
#springdoc.swagger-ui.enabled=true
#springdoc.cache.disabled=true
#
## Configuración de la API
#springdoc.version=1.0.0
#springdoc.api-docs.groups.enabled=true

#springdoc.swagger-ui.path=/swagger-ui.html
#springdoc.api-docs.path=/api-docs
#springdoc.version=1.0.0
#springdoc.title=Mi API Spring Boot
#springdoc.description=Documentación de mi API REST


